# Generated by Django 4.1.2 on 2022-10-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_appointment_date_time_alter_hospital_pass_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(default='+91 1234567890', max_length=100),
        ),
        migrations.AddField(
            model_name='hospital',
            name='phone_number',
            field=models.CharField(default='+91 1234567890', max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default='+91 1234567890', max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='pass_key',
            field=models.CharField(default='2mki60uwsg', max_length=100, unique=True),
        ),
    ]
