# Generated by Django 4.1.2 on 2022-10-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_doctor_phone_number_alter_hospital_pass_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='pass_key',
            field=models.CharField(default='27u1aqsdmn', max_length=100, unique=True),
        ),
    ]
