# Generated by Django 4.1.2 on 2022-10-24 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_medicinesforprescription_alter_hospital_pass_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalTestAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('recommendation', models.CharField(max_length=200)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OperationsAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('recommendation', models.CharField(max_length=200)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='hospital',
            name='pass_key',
            field=models.CharField(default='tmc3wd5xn4', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='OperationTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_deadline', models.DateField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.doctor')),
                ('operations', models.ManyToManyField(to='system.operationsavailable')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_deadline', models.DateField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.patient')),
                ('tests', models.ManyToManyField(to='system.medicaltestavailable')),
            ],
        ),
    ]
